<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { ChevronLeft, ChevronRight, Pencil, Eraser, Trash2, Upload, Mic, MicOff, Users, Monitor, X } from 'lucide-vue-next';
import * as pdfjs from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import type { User } from '../types';
import { api } from '../api';
import { getSocket } from '../socket';
import { useI18n } from '../i18n';
import { addRemoteIceCandidate, createPeerConnection, setRemoteDescription } from '../webrtc';
pdfjs.GlobalWorkerOptions.workerSrc = workerUrl;
type Stroke = { id: string; page: number; points: { x: number; y: number }[]; color: string; width: number; tool: 'pen' | 'eraser' };
type Participant = { userId: string; displayName: string; avatarColor: string; muted: boolean };
const props = defineProps<{ conversationId: string; pdfUrl: string | null; presenterId: string; currentUser: User }>();
const emit = defineEmits<{ end: [] }>(); const { t } = useI18n();
const presenter = computed(() => props.currentUser.id === props.presenterId), container = ref<HTMLElement>(), pdfCanvas = ref<HTMLCanvasElement>(), drawCanvas = ref<HTMLCanvasElement>(), screenVideo = ref<HTMLVideoElement>();
const activePdf = ref(props.pdfUrl), numPages = ref(0), page = ref(1), tool = ref<'pen' | 'eraser'>('pen'), color = ref('#ef4444'), width = ref(4), error = ref(''), uploadProgress = ref<number | null>(null), voiceActive = ref(false), muted = ref(false), participants = ref<Participant[]>([]), sharing = ref(false), remoteSharing = ref(false);
const strokes = new Map<number, Stroke[]>(), remoteStrokes = new Map<string, Stroke>(), peers = new Map<string, RTCPeerConnection>(), screenPeers = new Map<string, RTCPeerConnection>(), earlyIce = new Map<string, RTCIceCandidateInit[]>();
let pdf: pdfjs.PDFDocumentProxy | null = null, media: MediaStream | null = null, screenStream: MediaStream | null = null, drawStroke: Stroke | null = null, drawing = false, canvasW = 0, canvasH = 0;
const colors = ['#ef4444', '#3b82f6', '#22c55e', '#000000', '#ffffff', '#eab308'], widths = [2, 4, 8];
function renderStrokes() { const canvas = drawCanvas.value; if (!canvas || !canvasW || !canvasH) return; const ctx = canvas.getContext('2d')!, dpr = window.devicePixelRatio || 1; ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.save(); ctx.scale(dpr, dpr); const list = [...(strokes.get(page.value) || []), ...[...remoteStrokes.values()].filter(stroke => stroke.page === page.value), ...(drawStroke?.page === page.value ? [drawStroke] : [])]; for (const stroke of list) { if (!stroke.points.length) continue; ctx.save(); ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.lineWidth = stroke.width; ctx.globalCompositeOperation = stroke.tool === 'eraser' ? 'destination-out' : 'source-over'; ctx.strokeStyle = stroke.tool === 'eraser' ? '#000' : stroke.color; ctx.beginPath(); ctx.moveTo(stroke.points[0].x * canvasW, stroke.points[0].y * canvasH); for (const point of stroke.points.slice(1)) ctx.lineTo(point.x * canvasW, point.y * canvasH); if (stroke.points.length === 1) { ctx.arc(stroke.points[0].x * canvasW, stroke.points[0].y * canvasH, stroke.width / 2, 0, Math.PI * 2); ctx.fill(); } ctx.stroke(); ctx.restore(); } ctx.restore(); }
async function renderPage(target = page.value) { await nextTick(); const box = container.value, canvas = pdfCanvas.value, overlay = drawCanvas.value; if (!box || !canvas || !overlay) return; const dpr = window.devicePixelRatio || 1, cw = box.clientWidth, ch = box.clientHeight; let w: number, h: number; if (pdf && target <= pdf.numPages) { const p = await pdf.getPage(target), base = p.getViewport({ scale: 1 }), scale = Math.min((cw - 32) / base.width, (ch - 32) / base.height), view = p.getViewport({ scale }); w = Math.floor(view.width); h = Math.floor(view.height); canvas.width = w * dpr; canvas.height = h * dpr; canvas.style.width = `${w}px`; canvas.style.height = `${h}px`; await p.render({ canvas, canvasContext: canvas.getContext('2d')!, viewport: view, transform: [dpr, 0, 0, dpr, 0, 0] }).promise; } else { h = Math.min(ch - 32, 800); w = Math.min(cw - 32, 600, Math.floor(h / 1.414)); h = Math.floor(w * 1.414); canvas.width = w * dpr; canvas.height = h * dpr; canvas.style.width = `${w}px`; canvas.style.height = `${h}px`; const ctx = canvas.getContext('2d')!; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, w, h); } overlay.width = w * dpr; overlay.height = h * dpr; overlay.style.width = `${w}px`; overlay.style.height = `${h}px`; canvasW = w; canvasH = h; renderStrokes(); }
async function loadPdf(id: string | null) { pdf = null; numPages.value = 0; error.value = ''; if (id) { try { const blob = await api.getAttachmentBlob(id); pdf = await pdfjs.getDocument({ data: await blob.arrayBuffer() }).promise; numPages.value = pdf.numPages; } catch { error.value = t('pdfLoadError'); } } await renderPage(); }
watch(activePdf, value => { void loadPdf(value); });
function goto(target: number) { if (target < 1 || target > numPages.value) return; page.value = target; void renderPage(); if (presenter.value) getSocket()?.emit('wb_page', { conversationId: props.conversationId, page: target }); }
function point(event: PointerEvent) { const rect = drawCanvas.value!.getBoundingClientRect(); return { x: (event.clientX - rect.left) / rect.width, y: (event.clientY - rect.top) / rect.height }; }
function pointerDown(event: PointerEvent) { if (!presenter.value) return; event.preventDefault(); (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId); drawing = true; const p = point(event); drawStroke = { id: crypto.randomUUID(), page: page.value, points: [p], color: color.value, width: width.value, tool: tool.value }; getSocket()?.emit('wb_draw', { conversationId: props.conversationId, strokeId: drawStroke.id, page: page.value, points: [p], color: color.value, width: width.value, tool: tool.value, done: false }); renderStrokes(); }
function pointerMove(event: PointerEvent) { if (!drawing || !drawStroke) return; const p = point(event); drawStroke.points.push(p); getSocket()?.emit('wb_draw', { conversationId: props.conversationId, strokeId: drawStroke.id, page: page.value, points: [p], color: color.value, width: width.value, tool: tool.value, done: false }); renderStrokes(); }
function pointerUp() { if (!drawing || !drawStroke) return; drawing = false; const stroke = drawStroke, list = strokes.get(stroke.page) || []; list.push(stroke); strokes.set(stroke.page, list); getSocket()?.emit('wb_draw', { conversationId: props.conversationId, strokeId: stroke.id, page: stroke.page, points: [], color: stroke.color, width: stroke.width, tool: stroke.tool, done: true }); drawStroke = null; renderStrokes(); }
function clearPage() { if (!presenter.value) return; strokes.set(page.value, []); renderStrokes(); getSocket()?.emit('wb_clear', { conversationId: props.conversationId, page: page.value }); }
async function uploadPdf(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; uploadProgress.value = 0; try { const result = await api.uploadFile(file, props.conversationId); uploadProgress.value = 100; activePdf.value = result.attachmentId; strokes.clear(); page.value = 1; getSocket()?.emit('wb_pdf', { conversationId: props.conversationId, attachmentId: result.attachmentId }); } catch { error.value = t('pdfLoadError'); } finally { setTimeout(() => uploadProgress.value = null, 350); (event.target as HTMLInputElement).value = ''; } }
function queueIce(key: string, candidate: RTCIceCandidateInit) { const items = earlyIce.get(key) || []; if (items.length < 128) items.push(candidate); earlyIce.set(key, items); }
async function drainIce(key: string, pc: RTCPeerConnection) { for (const item of earlyIce.get(key) || []) await addRemoteIceCandidate(pc, item); earlyIce.delete(key); }
async function voicePeers(data: { conversationId: string; peers: string[]; participants?: Participant[] }) { if (data.conversationId !== props.conversationId) return; if (data.participants) participants.value = data.participants; if (!media) return; for (const id of data.peers) { const pc = await createPeerConnection(); peers.set(id, pc); await drainIce(`voice:${id}`, pc); media.getTracks().forEach(track => pc.addTrack(track, media!)); pc.ontrack = event => { if (event.streams[0]) { const audio = new Audio(); audio.srcObject = event.streams[0]; audio.autoplay = true; } }; pc.onicecandidate = event => event.candidate && getSocket()?.emit('wb_voice_ice', { conversationId: props.conversationId, targetUserId: id, candidate: event.candidate.toJSON() }); const offer = await pc.createOffer(); await pc.setLocalDescription(offer); getSocket()?.emit('wb_voice_offer', { conversationId: props.conversationId, targetUserId: id, offer: pc.localDescription }); } }
async function voiceOffer(data: { conversationId: string; from: string; offer: RTCSessionDescriptionInit }) { if (data.conversationId !== props.conversationId || !media) return; const pc = await createPeerConnection(); peers.set(data.from, pc); await drainIce(`voice:${data.from}`, pc); media.getTracks().forEach(track => pc.addTrack(track, media!)); pc.ontrack = event => { if (event.streams[0]) { const audio = new Audio(); audio.srcObject = event.streams[0]; audio.autoplay = true; } }; pc.onicecandidate = event => event.candidate && getSocket()?.emit('wb_voice_ice', { conversationId: props.conversationId, targetUserId: data.from, candidate: event.candidate.toJSON() }); await setRemoteDescription(pc, data.offer); const answer = await pc.createAnswer(); await pc.setLocalDescription(answer); getSocket()?.emit('wb_voice_answer', { conversationId: props.conversationId, targetUserId: data.from, answer: pc.localDescription }); }
async function voiceAnswer(data: { conversationId: string; from: string; answer: RTCSessionDescriptionInit }) { if (data.conversationId !== props.conversationId) return; const pc = peers.get(data.from); if (pc) await setRemoteDescription(pc, data.answer); }
async function joinVoice() { try { media = await navigator.mediaDevices.getUserMedia({ audio: true }); voiceActive.value = true; getSocket()?.emit('wb_voice_join', { conversationId: props.conversationId }); } catch { error.value = t('mediaPermissionDenied'); } }
function leaveVoice() { getSocket()?.emit('wb_voice_leave', { conversationId: props.conversationId }); media?.getTracks().forEach(track => track.stop()); media = null; for (const pc of peers.values()) pc.close(); peers.clear(); voiceActive.value = false; muted.value = false; participants.value = participants.value.filter(item => item.userId !== props.currentUser.id); }
function toggleMute() { const track = media?.getAudioTracks()[0]; if (!track) return; track.enabled = !track.enabled; muted.value = !track.enabled; getSocket()?.emit('wb_voice_mute', { conversationId: props.conversationId, muted: muted.value }); }
async function startShare() { try { screenStream = await navigator.mediaDevices.getDisplayMedia({ video: true }); sharing.value = true; if (screenVideo.value) screenVideo.value.srcObject = screenStream; getSocket()?.emit('wb_screen_start', { conversationId: props.conversationId }); screenStream.getVideoTracks()[0].addEventListener('ended', stopShare); } catch { error.value = t('screenShareFailed'); } }
function stopShare() { screenStream?.getTracks().forEach(track => track.stop()); screenStream = null; for (const pc of screenPeers.values()) pc.close(); screenPeers.clear(); if (screenVideo.value) screenVideo.value.srcObject = null; sharing.value = false; getSocket()?.emit('wb_screen_stop', { conversationId: props.conversationId }); }
async function screenWatcher(data: { conversationId: string; viewerId: string }) { if (data.conversationId !== props.conversationId || !screenStream) return; const pc = await createPeerConnection(); screenPeers.set(data.viewerId, pc); await drainIce(`screen:${data.viewerId}`, pc); screenStream.getTracks().forEach(track => pc.addTrack(track, screenStream!)); pc.onicecandidate = event => event.candidate && getSocket()?.emit('wb_screen_ice', { conversationId: props.conversationId, targetUserId: data.viewerId, candidate: event.candidate.toJSON() }); const offer = await pc.createOffer(); await pc.setLocalDescription(offer); getSocket()?.emit('wb_screen_offer', { conversationId: props.conversationId, targetUserId: data.viewerId, offer: pc.localDescription }); }
async function screenOffer(data: { conversationId: string; from: string; offer: RTCSessionDescriptionInit }) { if (data.conversationId !== props.conversationId) return; const pc = await createPeerConnection(); screenPeers.set(data.from, pc); await drainIce(`screen:${data.from}`, pc); pc.ontrack = event => { if (screenVideo.value && event.streams[0]) screenVideo.value.srcObject = event.streams[0]; }; pc.onicecandidate = event => event.candidate && getSocket()?.emit('wb_screen_ice', { conversationId: props.conversationId, targetUserId: data.from, candidate: event.candidate.toJSON() }); await setRemoteDescription(pc, data.offer); const answer = await pc.createAnswer(); await pc.setLocalDescription(answer); getSocket()?.emit('wb_screen_answer', { conversationId: props.conversationId, targetUserId: data.from, answer: pc.localDescription }); }
const activeScreen = computed(() => sharing.value || remoteSharing.value);
function onDraw(data: { conversationId: string; strokeId: string; page: number; points: Stroke['points']; color: string; width: number; tool: Stroke['tool']; done: boolean }) { if (data.conversationId !== props.conversationId) return; let stroke = remoteStrokes.get(data.strokeId); if (!stroke) { stroke = { id: data.strokeId, page: data.page, points: [...data.points], color: data.color, width: data.width, tool: data.tool }; remoteStrokes.set(data.strokeId, stroke); } else stroke.points.push(...data.points); if (data.done && stroke) { remoteStrokes.delete(data.strokeId); const list = strokes.get(stroke.page) || []; list.push(stroke); strokes.set(stroke.page, list); } renderStrokes(); }
function onPage(data: { conversationId: string; page: number }) { if (data.conversationId !== props.conversationId) return; page.value = data.page; void renderPage(data.page); }
function onClear(data: { conversationId: string; page: number }) { if (data.conversationId !== props.conversationId) return; strokes.set(data.page, []); renderStrokes(); }
function onPdf(data: { conversationId: string; pdfUrl: string | null }) { if (data.conversationId !== props.conversationId) return; activePdf.value = data.pdfUrl; strokes.clear(); page.value = 1; }
function onEnded(data: { conversationId: string }) { if (data.conversationId === props.conversationId) emit('end'); }
function onState(data: { conversationId: string; pdfUrl: string | null; currentPage: number; strokes?: Record<string, Stroke[]>; voiceParticipants?: Participant[]; screenShareActive?: boolean }) { if (data.conversationId !== props.conversationId) return; if (data.pdfUrl) activePdf.value = data.pdfUrl; if (data.strokes) { strokes.clear(); for (const [key, list] of Object.entries(data.strokes)) strokes.set(Number(key), list); } if (data.voiceParticipants) participants.value = data.voiceParticipants; page.value = data.currentPage || 1; if (data.screenShareActive) { remoteSharing.value = true; getSocket()?.emit('wb_screen_watch', { conversationId: props.conversationId }); } void renderPage(page.value); }
function onVoiceTrack(data: Participant) { participants.value = participants.value.some(item => item.userId === data.userId) ? participants.value.map(item => item.userId === data.userId ? { ...item, ...data } : item) : [...participants.value, data]; }
function onVoiceLeft(data: { userId: string }) { participants.value = participants.value.filter(item => item.userId !== data.userId); peers.get(data.userId)?.close(); peers.delete(data.userId); }
function onVoiceMuted(data: { userId: string; muted: boolean }) { participants.value = participants.value.map(item => item.userId === data.userId ? { ...item, muted: data.muted } : item); }
function onVoiceIce(data: { conversationId: string; from: string; candidate: RTCIceCandidateInit }) { if (data.conversationId !== props.conversationId) return; const pc = peers.get(data.from); if (pc) void addRemoteIceCandidate(pc, data.candidate); else queueIce(`voice:${data.from}`, data.candidate); }
function onScreenStarted(data: { conversationId: string }) { if (data.conversationId !== props.conversationId) return; remoteSharing.value = true; getSocket()?.emit('wb_screen_watch', { conversationId: props.conversationId }); }
function onScreenStopped(data: { conversationId: string }) { if (data.conversationId !== props.conversationId) return; remoteSharing.value = false; for (const pc of screenPeers.values()) pc.close(); screenPeers.clear(); if (screenVideo.value) screenVideo.value.srcObject = null; }
function onScreenAnswer(data: { conversationId: string; from: string; answer: RTCSessionDescriptionInit }) { if (data.conversationId === props.conversationId) { const pc = screenPeers.get(data.from); if (pc) void setRemoteDescription(pc, data.answer); } }
function onScreenIce(data: { conversationId: string; from: string; candidate: RTCIceCandidateInit }) { if (data.conversationId !== props.conversationId) return; const pc = screenPeers.get(data.from); if (pc) void addRemoteIceCandidate(pc, data.candidate); else queueIce(`screen:${data.from}`, data.candidate); }
function resize() { void renderPage(); }
function finish() { leaveVoice(); if (sharing.value) stopShare(); if (presenter.value) getSocket()?.emit('wb_end', { conversationId: props.conversationId }); emit('end'); }
onMounted(() => { const socket = getSocket(); if (!socket) return; socket.emit('wb_get_state', { conversationId: props.conversationId }); socket.on('wb_draw', onDraw); socket.on('wb_page_changed', onPage); socket.on('wb_cleared', onClear); socket.on('wb_pdf_loaded', onPdf); socket.on('wb_ended', onEnded); socket.on('wb_state', onState); socket.on('wb_voice_peers', voicePeers); socket.on('wb_voice_offer', voiceOffer); socket.on('wb_voice_answer', voiceAnswer); socket.on('wb_voice_ice', onVoiceIce); socket.on('wb_voice_joined', onVoiceTrack); socket.on('wb_voice_left', onVoiceLeft); socket.on('wb_voice_muted', onVoiceMuted); socket.on('wb_screen_started', onScreenStarted); socket.on('wb_screen_stopped', onScreenStopped); socket.on('wb_screen_watcher', screenWatcher); socket.on('wb_screen_offer', screenOffer); socket.on('wb_screen_answer', onScreenAnswer); socket.on('wb_screen_ice', onScreenIce); window.addEventListener('resize', resize); void loadPdf(activePdf.value); });
onBeforeUnmount(() => { const socket = getSocket(); for (const event of ['wb_draw','wb_page_changed','wb_cleared','wb_pdf_loaded','wb_ended','wb_state','wb_voice_peers','wb_voice_offer','wb_voice_answer','wb_voice_ice','wb_voice_joined','wb_voice_left','wb_voice_muted','wb_screen_started','wb_screen_stopped','wb_screen_watcher','wb_screen_offer','wb_screen_answer','wb_screen_ice']) socket?.off(event); leaveVoice(); screenStream?.getTracks().forEach(track => track.stop()); for (const pc of screenPeers.values()) pc.close(); window.removeEventListener('resize', resize); });
</script>
<template><div class="whiteboard-overlay"><div class="whiteboard-header"><div class="whiteboard-title">{{ t('whiteboard') }}</div><div v-if="numPages" class="whiteboard-page-nav"><button class="icon-btn" :disabled="page <= 1 || !presenter" @click="goto(page - 1)"><ChevronLeft :size="20"/></button><span class="whiteboard-page-num">{{ page }} / {{ numPages }}</span><button class="icon-btn" :disabled="page >= numPages || !presenter" @click="goto(page + 1)"><ChevronRight :size="20"/></button></div><button class="wb-voice-btn" :class="voiceActive ? muted ? 'muted' : 'active' : ''" @click="voiceActive ? toggleMute() : joinVoice()"><Mic v-if="voiceActive && !muted" :size="18"/><MicOff v-else :size="18"/><span>{{ voiceActive ? muted ? t('muted') : t('voiceOn') : t('joinVoice') }}</span></button><button v-if="voiceActive" class="wb-voice-leave-btn" @click="leaveVoice"><MicOff :size="18"/></button><button class="whiteboard-end-btn" @click="finish"><X :size="18"/><span>{{ presenter ? t('end') : t('leave') }}</span></button></div>
  <div v-if="participants.length" class="wb-participants-bar"><div class="wb-participants-label"><Users :size="14"/><span>{{ t('inCall', { count: participants.length }) }}</span></div><div class="wb-participants-list"><div v-for="person in participants" :key="person.userId" class="wb-participant" :class="{ self: person.userId === currentUser.id }"><div class="wb-participant-avatar" :style="{ background: person.avatarColor }">{{ person.displayName.charAt(0).toUpperCase() }}</div><span class="wb-participant-name">{{ person.userId === currentUser.id ? t('you') : person.displayName }}</span><span class="wb-participant-mic" :class="{ muted: person.muted }"><MicOff v-if="person.muted" :size="14"/><Mic v-else :size="14"/></span></div></div></div>
  <div ref="container" class="whiteboard-canvas-area"><div v-if="error" class="whiteboard-error" role="alert">{{ error }}</div><div class="whiteboard-canvas-wrap"><canvas ref="pdfCanvas" class="whiteboard-pdf-canvas" :style="{ display: activeScreen ? 'none' : undefined }"/><video ref="screenVideo" class="whiteboard-screen-video" autoplay playsinline muted :style="{ display: activeScreen ? 'block' : 'none' }"/><canvas ref="drawCanvas" class="whiteboard-draw-canvas" :style="{ cursor: presenter ? 'crosshair' : 'default' }" @pointerdown="pointerDown" @pointermove="pointerMove" @pointerup="pointerUp" @pointercancel="pointerUp"/></div><div v-if="uploadProgress !== null" class="whiteboard-upload-overlay"><div class="whiteboard-upload-progress"><div class="whiteboard-upload-bar"><div class="whiteboard-upload-fill" :style="{ width: `${uploadProgress}%` }"/></div><span class="whiteboard-upload-text">{{ t('processing') }}</span></div></div><div v-if="!activePdf && !error && uploadProgress === null && !activeScreen" class="whiteboard-placeholder">{{ presenter ? t('uploadPdfPrompt') : t('waitingForPresenter') }}</div></div>
  <div v-if="presenter" class="whiteboard-toolbar"><div class="whiteboard-tool-group"><button class="wb-tool-btn" :class="{ active: tool === 'pen' }" :title="t('pen')" @click="tool = 'pen'"><Pencil :size="18"/></button><button class="wb-tool-btn" :class="{ active: tool === 'eraser' }" :title="t('eraser')" @click="tool = 'eraser'"><Eraser :size="18"/></button><button class="wb-tool-btn" :title="t('clearPage')" @click="clearPage"><Trash2 :size="18"/></button></div><div class="whiteboard-tool-group wb-colors"><button v-for="c in colors" :key="c" class="wb-color-btn" :class="{ active: color === c }" :style="{ background: c, border: c === '#ffffff' ? '2px solid #666' : '2px solid transparent' }" @click="color = c"/></div><div class="whiteboard-tool-group wb-widths"><button v-for="w in widths" :key="w" class="wb-width-btn" :class="{ active: width === w }" @click="width = w"><span class="wb-width-dot" :style="{ width: `${w + 4}px`, height: `${w + 4}px` }"/></button></div><label class="wb-tool-btn wb-upload-btn" :title="t('uploadPdf')"><Upload :size="18"/><input type="file" accept=".pdf,application/pdf" style="display:none" @change="uploadPdf"/></label><button class="wb-tool-btn" :class="{ active: sharing }" :title="sharing ? t('stopSharing') : t('shareScreen')" @click="sharing ? stopShare() : startShare()"><Monitor :size="18"/></button></div>
</div></template>
